services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: flowfeedback-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuaSenhaForte!123
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-P", "SuaSenhaForte!123", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: flowfeedback-cache
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: flowfeedback-mq
    ports:
      - "5672:5672"
      - "15672:15672"